// Generated by CoffeeScript 1.4.0
(function() {
  var ExpressFlow, app;

  ExpressFlow = require("./app/js/express_flow.js");

  app = new ExpressFlow(__dirname);

  app.start();

  console.log("starting");

}).call(this);
