// Generated by CoffeeScript 1.4.0
(function() {
  var ExpressFlow, express,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  express = require("express");

  ExpressFlow = (function() {

    function ExpressFlow(dir) {
      this.dir = dir;
      this.renderError = __bind(this.renderError, this);

      this.renderIndex = __bind(this.renderIndex, this);

      this.definePaths = __bind(this.definePaths, this);

      this.config = __bind(this.config, this);

      this.start = __bind(this.start, this);

      this.app = express();
      this.config();
      this.definePaths();
    }

    ExpressFlow.prototype.start = function() {
      return this.app.listen(3001);
    };

    ExpressFlow.prototype.config = function() {
      var pub;
      pub = this.dir + "/public";
      this.app.use(express.cookieParser('doit_toit_now'));
      this.app.use(express.cookieSession());
      this.app.use(express["static"](pub));
      this.app.use(this.app.router);
      return this.app.set("views", this.dir + "/views");
    };

    ExpressFlow.prototype.definePaths = function() {
      return this.app.get("/", this.renderIndex);
    };

    ExpressFlow.prototype.renderIndex = function(req, res) {
      console.log("sending " + this.dir + "views/index.html");
      return res.sendfile(this.dir + "/views/index.html");
    };

    ExpressFlow.prototype.renderError = function(err, html) {};

    return ExpressFlow;

  })();

  module.exports = ExpressFlow;

}).call(this);
