// Generated by CoffeeScript 1.4.0
(function() {
  var ToitController, express,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  express = require("express");

  ToitController = (function() {

    function ToitController(dir) {
      this.dir = dir;
      this.renderError = __bind(this.renderError, this);

      this.updateTodos = __bind(this.updateTodos, this);

      this.renderIndex = __bind(this.renderIndex, this);

      this.definePaths = __bind(this.definePaths, this);

      this.config = __bind(this.config, this);

      this.start = __bind(this.start, this);

      this.app = express();
      this.config();
      this.definePaths();
    }

    ToitController.prototype.start = function() {
      return this.app.listen(3001);
    };

    ToitController.prototype.config = function() {
      var pub;
      pub = this.dir + "/public";
      this.app.use(express.bodyParser());
      this.app.use(express.cookieParser('doit_toit_now'));
      this.app.use(express.cookieSession());
      this.app.use(express["static"](pub));
      this.app.use(this.app.router);
      return this.app.set("views", this.dir + "/views");
    };

    ToitController.prototype.definePaths = function() {
      this.app.get("/", this.renderIndex);
      return this.app.post("/update/", this.updateTodos);
    };

    ToitController.prototype.renderIndex = function(req, res) {
      console.log("sending " + this.dir + "views/index.html");
      return res.sendfile(this.dir + "/views/index.html");
    };

    ToitController.prototype.updateTodos = function(req, res) {
      req.session.todos = req.body.todos;
      res.cookie('todos', req.body.todos, {
        maxAge: 1000 * 60 * 60 * 24 * 365
      });
      return res.send("Todos updated as " + req.session.todos);
    };

    ToitController.prototype.renderError = function(err, html) {};

    return ToitController;

  })();

  module.exports = ToitController;

}).call(this);
